---
- hosts: localhost
  become: yes

  roles:
    - geerlingguy.docker

  tasks:

  - name: Install Nginx Latest
    apt: name=nginx state=latest

  - name: Start Nginx Service
    service:
      name: nginx
      state: started