---
- hosts: localhost
  become: yes

  roles:
    - geerlingguy.docker

  tasks:

  - name: Install Nginx Latest
    apt: name=nginx state=latest

  - name: Start Nginx Service
    service:
      name: nginx
      state: started

  # - name: Clean artifact path
  #   file:
  #     state: absent
  #     path: "/var/www/html/"

  # - name: Git Pull the code from repository
  #   git: repo="https://github.com/bennojoy/mywebapp.git" dest=/var/www/html/ force=yes